### PR TITLE
Remove ha.ckers and w3schools references

### PR DESCRIPTION
**Pull request by robocoder**

### CODE REVIEW

**Comment by andresriancho** [comment]
:+1: on removing hackers.org site

Why do you want to remove the w3shcools links?

**Comment by andresriancho** [comment]
Removed offline site to fix build
https://github.com/vulndb/data/commit/b970881d7f61fc4ec8e37f928bf49120f1e590f7
https://circleci.com/gh/vulndb/data/50

**Comment by robocoder** [comment]
Out of personal preference to not link to an adware supported site.  It's your call.  Consumers can easily filter the sdk's response.

**Comment by robocoder** [comment]
Abandoned

**Pull request closed without merging**
